"""add artists and artworks

Revision ID: 196e30028e19
Revises: 2df12c7409ae
Create Date: 2026-07-25 14:46:15.307681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196e30028e19'
down_revision: Union[str, Sequence[str], None] = '2df12c7409ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id')
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_table('artworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('medium', sa.String(length=255), nullable=True),
    sa.Column('dimensions', sa.String(length=255), nullable=True),
    sa.Column('acquisition_date', sa.String(length=100), nullable=True),
    sa.Column('credit', sa.String(length=255), nullable=True),
    sa.Column('catalogue', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('classification', sa.String(length=255), nullable=True),
    sa.Column('object_number', sa.String(length=100), nullable=True),
    sa.Column('diameter_cm', sa.Float(), nullable=True),
    sa.Column('circumference_cm', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('length_cm', sa.Float(), nullable=True),
    sa.Column('width_cm', sa.Float(), nullable=True),
    sa.Column('depth_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artwork_id')
    )
    op.create_index(op.f('ix_artworks_id'), 'artworks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artworks_id'), table_name='artworks')
    op.drop_table('artworks')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
